// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: market_viewer

#ifndef UI_AITEXTSCREEN_H
#define UI_AITEXTSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_aiTextScreen
extern void ui_aiTextScreen_screen_init(void);
extern void ui_aiTextScreen_screen_destroy(void);
extern void ui_event_aiTextScreen(lv_event_t * e);
extern lv_obj_t * ui_aiTextScreen;
extern lv_obj_t * ui_aiTextPanel;
extern lv_obj_t * ui_aiTextLabel;
extern void ui_event_aiTextReadButton(lv_event_t * e);
extern lv_obj_t * ui_aiTextReadButton;
extern lv_obj_t * ui_robotIcon;
extern lv_obj_t * ui_aiTextScreenPromptPanel;
extern lv_obj_t * ui_aiPromptTitleLabel;
extern lv_obj_t * ui_aiPromptLabel;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

