// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: market_viewer

#include "ui.h"

lv_obj_t * ui_aiTextScreen = NULL;
lv_obj_t * ui_aiTextPanel = NULL;
lv_obj_t * ui_aiTextLabel = NULL;
lv_obj_t * ui_aiTextReadButton = NULL;
lv_obj_t * ui_robotIcon = NULL;
lv_obj_t * ui_aiTextScreenPromptPanel = NULL;
lv_obj_t * ui_aiPromptTitleLabel = NULL;
lv_obj_t * ui_aiPromptLabel = NULL;
// event funtions
void ui_event_aiTextScreen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_BOTTOM) {
        lv_indev_wait_release(lv_indev_get_act());
        requestScreenDataRefresh(e);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        swipePrevScreen(e);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        swipeNextScreen(e);
    }
}

void ui_event_aiTextReadButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        openWifiPortal(e);
    }
}

// build funtions

void ui_aiTextScreen_screen_init(void)
{
    ui_aiTextScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_aiTextScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_aiTextScreen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_aiTextScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_aiTextScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_aiTextScreen, &ui_img_purple_background_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_tiled(ui_aiTextScreen, true, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_aiTextPanel = lv_obj_create(ui_aiTextScreen);
    lv_obj_set_width(ui_aiTextPanel, 484);
    lv_obj_set_height(ui_aiTextPanel, 318);
    lv_obj_set_x(ui_aiTextPanel, 0);
    lv_obj_set_y(ui_aiTextPanel, -35);
    lv_obj_set_align(ui_aiTextPanel, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_aiTextPanel, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_aiTextPanel, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_add_flag(ui_aiTextPanel, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_bg_color(ui_aiTextPanel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_aiTextPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_aiTextPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_aiTextPanel, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_pad_left(ui_aiTextPanel, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_aiTextPanel, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_aiTextPanel, 150, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_aiTextPanel, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_aiTextLabel = lv_label_create(ui_aiTextPanel);
    lv_obj_set_width(ui_aiTextLabel, 377);
    lv_obj_set_height(ui_aiTextLabel, LV_SIZE_CONTENT);    /// 297
    lv_obj_set_x(ui_aiTextLabel, 8);
    lv_obj_set_y(ui_aiTextLabel, 134);
    lv_obj_set_align(ui_aiTextLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_aiTextLabel,
                      "Bitcoin is trading around $68,000 today, showing modest gains amid market consolidation. Sentiment is currently in \\\"extreme fear\\\" as it attempts to stabilize after a volatile start to 2026. Institutional outflows from Bitcoin ETFs and ongoing regulatory uncertainty are weighing on the market.");
    lv_obj_set_style_text_color(ui_aiTextLabel, lv_color_hex(0xE0E0E0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_aiTextLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_aiTextLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_aiTextLabel, &ui_font_monoLight30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_aiTextReadButton = lv_btn_create(ui_aiTextScreen);
    lv_obj_set_width(ui_aiTextReadButton, 90);
    lv_obj_set_height(ui_aiTextReadButton, 90);
    lv_obj_set_x(ui_aiTextReadButton, 0);
    lv_obj_set_y(ui_aiTextReadButton, 180);
    lv_obj_set_align(ui_aiTextReadButton, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_aiTextReadButton, LV_STATE_DISABLED);       /// States
    lv_obj_add_flag(ui_aiTextReadButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_aiTextReadButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_aiTextReadButton, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_aiTextReadButton, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_grayBright);
    ui_object_set_themeable_style_property(ui_aiTextReadButton, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_grayBright);
    lv_obj_set_style_bg_img_src(ui_aiTextReadButton, &ui_img_1028167261, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_robotIcon = lv_img_create(ui_aiTextScreen);
    lv_img_set_src(ui_robotIcon, &ui_img_768942523);
    lv_obj_set_width(ui_robotIcon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_robotIcon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_robotIcon, 0);
    lv_obj_set_y(ui_robotIcon, -215);
    lv_obj_set_align(ui_robotIcon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_robotIcon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_robotIcon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_img_recolor(ui_robotIcon, lv_color_hex(0xD8BEFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(ui_robotIcon, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_aiTextScreenPromptPanel = lv_obj_create(ui_aiTextScreen);
    lv_obj_set_width(ui_aiTextScreenPromptPanel, 396);
    lv_obj_set_height(ui_aiTextScreenPromptPanel, 270);
    lv_obj_set_x(ui_aiTextScreenPromptPanel, 0);
    lv_obj_set_y(ui_aiTextScreenPromptPanel, -20);
    lv_obj_set_align(ui_aiTextScreenPromptPanel, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_aiTextScreenPromptPanel, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_aiTextScreenPromptPanel, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_aiTextScreenPromptPanel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_aiTextScreenPromptPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_aiTextScreenPromptPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_aiPromptTitleLabel = lv_label_create(ui_aiTextScreenPromptPanel);
    lv_obj_set_width(ui_aiPromptTitleLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_aiPromptTitleLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_aiPromptTitleLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_aiPromptTitleLabel, "AI PROMPT:");
    lv_obj_set_style_text_color(ui_aiPromptTitleLabel, lv_color_hex(0x3E88B4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_aiPromptTitleLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_aiPromptTitleLabel, &ui_font_monoBold60, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_aiPromptLabel = lv_label_create(ui_aiTextScreenPromptPanel);
    lv_obj_set_width(ui_aiPromptLabel, 309);
    lv_obj_set_height(ui_aiPromptLabel, LV_SIZE_CONTENT);    /// 168
    lv_obj_set_align(ui_aiPromptLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_aiPromptLabel, "some simple prompt");
    lv_obj_set_style_text_color(ui_aiPromptLabel, lv_color_hex(0x70B8DE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_aiPromptLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_aiPromptLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_aiPromptLabel, &ui_font_mono30, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_aiTextReadButton, ui_event_aiTextReadButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_aiTextScreen, ui_event_aiTextScreen, LV_EVENT_ALL, NULL);

}

void ui_aiTextScreen_screen_destroy(void)
{
    if(ui_aiTextScreen) lv_obj_del(ui_aiTextScreen);

    // NULL screen variables
    ui_aiTextScreen = NULL;
    ui_aiTextPanel = NULL;
    ui_aiTextLabel = NULL;
    ui_aiTextReadButton = NULL;
    ui_robotIcon = NULL;
    ui_aiTextScreenPromptPanel = NULL;
    ui_aiPromptTitleLabel = NULL;
    ui_aiPromptLabel = NULL;

}
