// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: market_viewer

#ifndef UI_BRIGHTNESSSCREEN_H
#define UI_BRIGHTNESSSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_brightnessScreen
extern void ui_brightnessScreen_screen_init(void);
extern void ui_brightnessScreen_screen_destroy(void);
extern void ui_event_brightnessScreen(lv_event_t * e);
extern lv_obj_t * ui_brightnessScreen;
extern void ui_event_brightnessArc(lv_event_t * e);
extern lv_obj_t * ui_brightnessArc;
extern lv_obj_t * ui_brightnessLabel;
extern lv_obj_t * ui_brightnessValueLabel;
extern void ui_event_brightnessButtonBack(lv_event_t * e);
extern lv_obj_t * ui_brightnessButtonBack;
extern lv_obj_t * ui_brightnessIcon;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

