// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: market_viewer

#ifndef UI_CLOCKSCREEN_H
#define UI_CLOCKSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_clockScreen
extern void ui_clockScreen_screen_init(void);
extern void ui_clockScreen_screen_destroy(void);
extern void ui_event_clockScreen(lv_event_t * e);
extern lv_obj_t * ui_clockScreen;
extern lv_obj_t * ui_clockGaugeImage;
extern lv_obj_t * ui_timezoneLabel;
extern lv_obj_t * ui_timeLabel;
extern lv_obj_t * ui_clockNeedleSecond;
extern lv_obj_t * ui_clockNeedleMinute;
extern lv_obj_t * ui_digitalClockBackground;
extern lv_obj_t * ui_digitalTimeLabel;
extern lv_obj_t * ui_digitalTimezoneLabel;
extern lv_obj_t * ui_digitalDateLabel;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

