// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: market_viewer

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void toggleTurnOff(lv_event_t * e);
void toggleRotationSettings(lv_event_t * e);
void setBrightnessFromArc(lv_event_t * e);
void setVolumeFromArc(lv_event_t * e);
void updateWifiScreenStatusOnLoad(lv_event_t * e);
void openWifiPortal(lv_event_t * e);
void resetWifiConfig(lv_event_t * e);

//custom functions
void changeWifiScreenConnected();
void changeWifiScreenNotConnected();

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
