// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: first_test

#include "ui.h"
#include <Arduino.h>
#include "HardwareDriver.h"
#include "esp32-hal-cpu.h"
#include "AudioManager.h"
#include "WifiConfig.h"

//global shield to not control screen when it is off
lv_obj_t * blackout_shield = NULL;

void toggleTurnOff(lv_event_t * e)
{        
       
    if (isScreenOff) {
        Serial.println("Screen waking up!");
        
        setCpuFrequencyMhz(240); // drop speed when device is 'turned on'
        Serial.println(currentBrightness);
        set_brightness_percentage(currentBrightness);
        isScreenOff = false;

        if (blackout_shield != NULL) {
            lv_obj_del(blackout_shield);
            blackout_shield = NULL; 
        }
    } else {
        Serial.println("Screen going to sleep");

        setCpuFrequencyMhz(80); // drop speed when device is 'turned off'
        set_brightness(0);
        isScreenOff = true;

        //CREATE THE SHIELD
        blackout_shield = lv_obj_create(lv_layer_top());        
        lv_obj_set_size(blackout_shield, LV_PCT(100), LV_PCT(100));        
        lv_obj_set_style_bg_opa(blackout_shield, 0, 0);
        lv_obj_set_style_border_width(blackout_shield, 0, 0);        
        lv_obj_add_flag(blackout_shield, LV_OBJ_FLAG_CLICKABLE);
        lv_obj_clear_flag(blackout_shield, LV_OBJ_FLAG_SCROLLABLE);
        lv_obj_add_event_cb(blackout_shield, toggleTurnOff, LV_EVENT_CLICKED, NULL);
    }    
}

void setBrightnessFromArc(lv_event_t * e)
{
    lv_obj_t * slider = lv_event_get_target(e);
    int32_t percentage = lv_arc_get_value(slider);
        
    Serial.println("setting brightness to: " + percentage);
    currentBrightness = percentage;

    set_brightness_percentage(percentage);
}

void setVolumeFromArc(lv_event_t * e)
{
    lv_obj_t * arc = lv_event_get_target(e);
    int32_t percentage = lv_arc_get_value(arc);
    
    Serial.println("Setting volume to: " + String(percentage));
    set_volume_percentage(percentage);

    // play sound to verify volume
    play_beep((percentage + 100) * 5, 50);
}

void toggleRotationSettings(lv_event_t * e)
{
    shouldRotate = !shouldRotate;
}

void openWifiPortal(lv_event_t * e)
{
    Serial.println("Opening WiFi configuration portal...");
    
    // Show a message on screen (optional)
    // You could create a loading screen here
    
    bool success = start_wifi_portal();
    
    if (success) {
        Serial.println("WiFi configured!");
        play_beep(1000, 100);  // Success beep
    } else {
        Serial.println("WiFi config cancelled/failed");
        play_beep(400, 200);  // Error beep
    }
}

void resetWifiConfig(lv_event_t * e)
{
    Serial.println("Resetting WiFi configuration...");
    reset_wifi_config();
    changeWifiScreenNotConnected();
    play_beep(600, 100);
}

void updateWifiScreenStatusOnLoad(lv_event_t * e) {
    if (is_wifi_connected()) {
        changeWifiScreenConnected();
    } else {
        changeWifiScreenNotConnected();
    }
}

void changeWifiScreenNotConnected() {
    //change the connection status
    lv_label_set_text(ui_connectionLabel, "NOT CONNECTED");
    lv_obj_set_style_bg_color(ui_wifiConnectionRoundIndicator, lv_color_hex(_ui_theme_color_redDark[0]), LV_PART_MAIN);
    //display the current wifif ssid
    lv_obj_add_flag(ui_connectedWifiContainer, LV_OBJ_FLAG_HIDDEN);
}

void changeWifiScreenConnected() {
    //change the connection status
    lv_label_set_text(ui_connectionLabel, "CONNECTED");
    lv_obj_set_style_bg_color(ui_wifiConnectionRoundIndicator, lv_color_hex(0x1ec20c), LV_PART_MAIN);
    //display the current wifif ssid
    lv_label_set_text(ui_connectedWifiSSIDLabel, get_connected_ssid());
    lv_obj_clear_flag(ui_connectedWifiContainer, LV_OBJ_FLAG_HIDDEN);
}
