// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: market_viewer

#ifndef UI_MARKETDATASETTINGSCREEN_H
#define UI_MARKETDATASETTINGSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_marketDataSettingScreen
extern void ui_marketDataSettingScreen_screen_init(void);
extern void ui_marketDataSettingScreen_screen_destroy(void);
extern void ui_event_marketDataSettingScreen(lv_event_t * e);
extern lv_obj_t * ui_marketDataSettingScreen;
extern lv_obj_t * ui_marketDataSettingsLabel;
extern lv_obj_t * ui_marketDataSettingMainPanel;
extern lv_obj_t * ui_simpleDispalyCont;
extern lv_obj_t * ui_simpleDisplayLabel;
extern lv_obj_t * ui_simpleDisplaySwitch;
extern lv_obj_t * ui_displayGraphCont;
extern lv_obj_t * ui_displayChartLabel;
extern lv_obj_t * ui_displayGraphSwitch;
extern lv_obj_t * ui_candleChartCont;
extern lv_obj_t * ui_candleChartLabel;
extern lv_obj_t * ui_candleChartSwitch;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

