// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: market_viewer

#include "ui.h"

lv_obj_t * ui_stockScreen = NULL;
lv_obj_t * ui_stockPriceLabel = NULL;
lv_obj_t * ui_stockSymbolLabel = NULL;
lv_obj_t * ui_stockPriceChangeLabel = NULL;
lv_obj_t * ui_stockCurrencyLabel = NULL;
lv_obj_t * ui_stockTimeFrameLabel = NULL;
// event funtions
void ui_event_stockScreen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        swipePrevScreen(e);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        swipeNextScreen(e);
    }
}

// build funtions

void ui_stockScreen_screen_init(void)
{
    ui_stockScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_stockScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_stockScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_stockScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_stockScreen, lv_color_hex(0xA30000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_stockScreen, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_stockScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_stockScreen, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_stockPriceLabel = lv_label_create(ui_stockScreen);
    lv_obj_set_width(ui_stockPriceLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_stockPriceLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_stockPriceLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_stockPriceLabel, "78952");
    lv_obj_set_style_text_font(ui_stockPriceLabel, &ui_font_monoBold60, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_stockSymbolLabel = lv_label_create(ui_stockScreen);
    lv_obj_set_width(ui_stockSymbolLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_stockSymbolLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_stockSymbolLabel, 1);
    lv_obj_set_y(ui_stockSymbolLabel, -200);
    lv_obj_set_align(ui_stockSymbolLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_stockSymbolLabel, "AAPL");
    lv_obj_set_style_text_font(ui_stockSymbolLabel, &ui_font_Mono20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_stockPriceChangeLabel = lv_label_create(ui_stockScreen);
    lv_obj_set_width(ui_stockPriceChangeLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_stockPriceChangeLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_stockPriceChangeLabel, 0);
    lv_obj_set_y(ui_stockPriceChangeLabel, 60);
    lv_obj_set_align(ui_stockPriceChangeLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_stockPriceChangeLabel, "-20%");
    lv_obj_set_style_text_font(ui_stockPriceChangeLabel, &ui_font_mono30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_stockPriceChangeLabel, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_stockPriceChangeLabel, lv_color_hex(0xDF0A0A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_stockPriceChangeLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_stockPriceChangeLabel, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_stockPriceChangeLabel, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_stockPriceChangeLabel, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_stockPriceChangeLabel, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_stockCurrencyLabel = lv_label_create(ui_stockScreen);
    lv_obj_set_width(ui_stockCurrencyLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_stockCurrencyLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_stockCurrencyLabel, 0);
    lv_obj_set_y(ui_stockCurrencyLabel, -171);
    lv_obj_set_align(ui_stockCurrencyLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_stockCurrencyLabel, "USD");
    lv_obj_set_style_text_font(ui_stockCurrencyLabel, &ui_font_Mono20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_stockTimeFrameLabel = lv_label_create(ui_stockScreen);
    lv_obj_set_width(ui_stockTimeFrameLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_stockTimeFrameLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_stockTimeFrameLabel, 0);
    lv_obj_set_y(ui_stockTimeFrameLabel, 200);
    lv_obj_set_align(ui_stockTimeFrameLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_stockTimeFrameLabel, "1day");
    lv_obj_set_style_text_font(ui_stockTimeFrameLabel, &ui_font_Mono20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_stockScreen, ui_event_stockScreen, LV_EVENT_ALL, NULL);

}

void ui_stockScreen_screen_destroy(void)
{
    if(ui_stockScreen) lv_obj_del(ui_stockScreen);

    // NULL screen variables
    ui_stockScreen = NULL;
    ui_stockPriceLabel = NULL;
    ui_stockSymbolLabel = NULL;
    ui_stockPriceChangeLabel = NULL;
    ui_stockCurrencyLabel = NULL;
    ui_stockTimeFrameLabel = NULL;

}
