// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: market_viewer

#ifndef UI_STOCKSCREEN_H
#define UI_STOCKSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_stockScreen
extern void ui_stockScreen_screen_init(void);
extern void ui_stockScreen_screen_destroy(void);
extern void ui_event_stockScreen(lv_event_t * e);
extern lv_obj_t * ui_stockScreen;
extern lv_obj_t * ui_stockPriceLabel;
extern lv_obj_t * ui_stockSymbolLabel;
extern lv_obj_t * ui_stockPriceChangeLabel;
extern lv_obj_t * ui_stockCurrencyLabel;
extern lv_obj_t * ui_stockTimeFrameLabel;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

