// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: market_viewer

#ifndef UI_SCREENSSCREEN_H
#define UI_SCREENSSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_screensScreen
extern void ui_screensScreen_screen_init(void);
extern void ui_screensScreen_screen_destroy(void);
extern void ui_event_screensScreen(lv_event_t * e);
extern lv_obj_t * ui_screensScreen;
extern lv_obj_t * ui_screensLabel;
extern lv_obj_t * ui_screensListPanel;
extern lv_obj_t * ui_screenListItemLabelExample;
extern lv_obj_t * ui_screenNotFetchedLabel;
extern void ui_event_volumeButtonBack3(lv_event_t * e);
extern lv_obj_t * ui_volumeButtonBack3;
extern void ui_event_screensRefetchButton(lv_event_t * e);
extern lv_obj_t * ui_screensRefetchButton;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

