// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: market_viewer

#ifndef _UI_THEMES_H
#define _UI_THEMES_H

#ifdef __cplusplus
extern "C" {
#endif

#define UI_THEME_COLOR_GRAYBRIGHT 0
#define UI_THEME_COLOR_REDDARK 1
#define UI_THEME_COLOR_GRAYDARK 2
#define UI_THEME_COLOR_YELLOWDARK 3
#define UI_THEME_COLOR_YELLOWBRIGHT 4

#define UI_THEME_DEFAULT 0

extern const ui_theme_variable_t _ui_theme_color_grayBright[1];
extern const ui_theme_variable_t _ui_theme_alpha_grayBright[1];

extern const ui_theme_variable_t _ui_theme_color_redDark[1];
extern const ui_theme_variable_t _ui_theme_alpha_redDark[1];

extern const ui_theme_variable_t _ui_theme_color_grayDark[1];
extern const ui_theme_variable_t _ui_theme_alpha_grayDark[1];

extern const ui_theme_variable_t _ui_theme_color_yellowDark[1];
extern const ui_theme_variable_t _ui_theme_alpha_yellowDark[1];

extern const ui_theme_variable_t _ui_theme_color_yellowBright[1];
extern const ui_theme_variable_t _ui_theme_alpha_yellowBright[1];

extern const uint32_t * ui_theme_colors[1];
extern const uint8_t * ui_theme_alphas[1];
extern uint8_t ui_theme_idx;

void ui_theme_set(uint8_t theme_idx);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
