// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: market_viewer

#include "ui.h"


const ui_theme_variable_t _ui_theme_color_grayBright[1] = {0x4A484A};
const ui_theme_variable_t _ui_theme_alpha_grayBright[1] = {255};

const ui_theme_variable_t _ui_theme_color_redDark[1] = {0x9C0808};
const ui_theme_variable_t _ui_theme_alpha_redDark[1] = {255};

const ui_theme_variable_t _ui_theme_color_grayDark[1] = {0x323232};
const ui_theme_variable_t _ui_theme_alpha_grayDark[1] = {255};

const ui_theme_variable_t _ui_theme_color_yellowDark[1] = {0x83A510};
const ui_theme_variable_t _ui_theme_alpha_yellowDark[1] = {255};

const ui_theme_variable_t _ui_theme_color_yellowBright[1] = {0xE6D239};
const ui_theme_variable_t _ui_theme_alpha_yellowBright[1] = {255};
uint8_t ui_theme_idx = UI_THEME_DEFAULT;


void ui_theme_set(uint8_t theme_idx)
{
    ui_theme_idx = theme_idx;
    _ui_theme_set_variable_styles(UI_VARIABLE_STYLES_MODE_FOLLOW);
}

