// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: market_viewer

#ifndef UI_VOLUMESCREEN_H
#define UI_VOLUMESCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_volumeScreen
extern void ui_volumeScreen_screen_init(void);
extern void ui_volumeScreen_screen_destroy(void);
extern lv_obj_t * ui_volumeScreen;
extern void ui_event_volumeArc(lv_event_t * e);
extern lv_obj_t * ui_volumeArc;
extern lv_obj_t * ui_volumeLabel;
extern lv_obj_t * ui_volumeValueLabel;
extern void ui_event_volumeButtonBack(lv_event_t * e);
extern lv_obj_t * ui_volumeButtonBack;
extern lv_obj_t * ui_volumeIcon;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

