// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: market_viewer

#ifndef UI_WIFISCREEN_H
#define UI_WIFISCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_wifiScreen
extern void ui_wifiScreen_screen_init(void);
extern void ui_wifiScreen_screen_destroy(void);
extern void ui_event_wifiScreen(lv_event_t * e);
extern lv_obj_t * ui_wifiScreen;
extern lv_obj_t * ui_mainContainerWifi;
extern lv_obj_t * ui_connectionInfoContainer;
extern lv_obj_t * ui_wifiConnectionRoundIndicator;
extern lv_obj_t * ui_connectionLabel;
extern lv_obj_t * ui_connectedWifiContainer;
extern lv_obj_t * ui_connectedWifiSSIDLabel;
extern lv_obj_t * ui_connectedWifiIcon;
extern lv_obj_t * ui_wifiContainersButtons;
extern void ui_event_wifiConfigButton(lv_event_t * e);
extern lv_obj_t * ui_wifiConfigButton;
extern void ui_event_wifiResetButton(lv_event_t * e);
extern lv_obj_t * ui_wifiResetButton;
extern lv_obj_t * ui_wifiLabel;
extern void ui_event_volumeButtonBack2(lv_event_t * e);
extern lv_obj_t * ui_volumeButtonBack2;
extern lv_obj_t * ui_overlayWifiContainer;
extern lv_obj_t * ui_overlayWifiLabel1;
extern lv_obj_t * ui_overlayWifiSSIDLabel;
extern lv_obj_t * ui_overlayWifiSSIDLabelValue;
extern lv_obj_t * ui_overlayWifiPwdLabel;
extern lv_obj_t * ui_overlayWifiPwdLabelValue;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

